config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sample/index'
  get 'header/edit'
  get 'default_site', to: 'home#change_site'
  resources 'cms', controller: :home do
    resources :header, only: [:edit, :update]
    resources :banner, only: [:edit, :update]
    resources :custom_product, only: [:edit, :update]
    resources :widget, only: [:show, :edit, :update]
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
    @header = Header.find(@theme.header_id)
    @menus = @header.menus
    @logo = @header.logo
    @renderer = ERB.new(@theme.body)
    @hbody = ERB.new(@theme.hbody)
    @detail = ERB.new(@theme.detail)
  end

  def change_site
    Widget.all.each do |w|
      w.published = false
      w.save
    end
    redirect_to spree_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ecommerce CMS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Shop</a>
         </li>
         <li class="nav-item active">
         <a href="/default_site" class="btn btn-primary margin-button">Set as default site</a>
         </li>
    </ul>
  </div>
</nav>
<div class="row">
    <div class="container">
        <h1>Themes</h1>
            <div class="row">
                <% @themes.each do |theme| %>
                    <div class="col-4">
                        <div class="card card-body" style="height: 50rem;">
                            <%= link_to cm_path(theme) do %>
                                <%= image_tag theme.name + ".png" %>
                            <% end %>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/home/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ecommerce CMS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/cms">CMS</a>
         </li>
         <li class="nav-item active">
            <a class="nav-link" href="/">Shop</a>
         </li>
    </ul>
  </div>
</nav>
<div>
    <div class="page-header">
        <a href="<%= cm_widget_path(@theme) %>" class="btn btn-primary margin-button">Create widget</a>
    </div>
    <div>
      <%= render :inline => @detail.result(binding), :layout => false%>
      <%= render :inline => @hbody.result(binding), :layout => false%>
      <%= render :inline => @renderer.result(binding), :layout => false%>
    </div>
</div>